language: go
sudo: required

services:
  - docker
 
before_install:
  - export TZ='Asia/Shanghai' # 更改时区
  - docker build -t registry.heroku.com/"$HEROKU_APPNAME"/web .
  - docker login -u "$HEROKU_EMAIL" -p "$HEROKU_APIKEY" registry.heroku.com
  - docker push registry.heroku.com/"$HEROKU_APPNAME"/web
  
#  - docker run -d -p 127.0.0.1:8081:8081 registry.heroku.com/"$HEROKU_APPNAME"/web /bin/sh -c "/entrypoint.sh && supervisord && supervisorctl update && supervisorctl stop v2ray && supervisorctl status && v2ray -config=/etc/v2ray/config.json"
#   && tail -f /var/log/v2ray/status.log
#  - docker ps -a
install:
  - docker run -d registry.heroku.com/"$HEROKU_APPNAME"/web

# before_script:

script:    #测试
  - docker ps
  
after_script:
  - docker run -d registry.heroku.com/"$HEROKU_APPNAME"/web
  # /bin/sh -c "/entrypoint.sh && supervisord && supervisorctl update && supervisorctl stop v2ray && supervisorctl status && v2ray -config=/etc/v2ray/config.json"
  # -p 127.0.0.1:80:80 
