language: go
sudo: required

services:
  - docker
 
before_install:
  - docker build -t registry.heroku.com/"$HEROKU_APPNAME"/web .
  - docker login -u "$HEROKU_EMAIL" -p "$HEROKU_APIKEY" registry.heroku.com
  - docker push registry.heroku.com/"$HEROKU_APPNAME"/web
  
  - docker run -d -p 127.0.0.1:8081:8081 registry.heroku.com/"$HEROKU_APPNAME"/web /bin/sh -c "cd /etc/v2ray; echo -e -n "$CONFIG_JSON1" > config.json; echo -e -n "$PORT"  >> config.json; echo -e -n "$CONFIG_JSON2"  >> config.json; echo -e -n "$UUID"  >> config.json; echo -e -n "$CONFIG_JSON3" >> config.json; supervisord -c /etc/supervisord.conf; supervisorctl restart v2ray;"
  - docker ps -a

script:
  - echo "ok"
